name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: divideprojects/poetry-export-requirements-action@v1
      with:
        without-hashes: true
        outfile-name: requirements.txt
        
    - id: bump_version
      name: Create bump and changelog
      uses: commitizen-tools/commitizen-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Print Version
      run: echo "Bumped to version ${{ steps.bump_version.outputs.version }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image for kargo-demo-app
      uses: docker/build-push-action@v2
      with:
        context: api
        push: true
        tags: |
          ghcr.io/tautcius/kargo-demo-app:${{ steps.bump_version.outputs.version }}
          ghcr.io/tautcius/kargo-demo-app:latest
